# Generated by Django 4.1 on 2022-09-03 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_store_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='message',
        ),
    ]
